Git step: pass the git submodule foreach subcommand as single argument to prevent options aimed at the subcommand to be interpreted as options for the "git submodule foreach" command.
This fixes the following error in git steps (using Git 2.21):

    $ git submodule foreach --recursive git clean -f -f -d
    error: unknown switch `f'
    usage: git submodule--helper foreach [--quiet] [--recursive] <command>

(cherry picked from commit 8bcd31635705f08be703f54e410032a9b5afa127)