worker: Improve robustness of requestAvatarId()
The following exception is sometimes observed in Buildbot unit tests:

Traceback (most recent call last):
File "/.../site-packages/twisted/internet/defer.py", line 2017, in
_inlineCallbacks
    result = context.run(gen.send, result)
File "/.../master/buildbot/worker/protocols/manager/pb.py", line 102, in
requestAvatarId
    eventually(self.master.initLock.release)
builtins.AttributeError: 'NoneType' object has no attribute 'initLock'

This means that there is a race condition during master shutdown. Most
likely, Dispatcher is disconnected from parent service during master
shutdown. Note that master is None even before submitting the callback
to eventually(), so the race condition is not related to it.